// Yörükhan oyunlarının İngilizce adı, açıklaması ve kontrolleri (veritabanındaki kayıtlar Türkçe).
// Anahtar: yg_games tablosundaki oyun id'si. Yeni resmi oyun eklenince buraya da eklenebilir.
export const GAMES_EN = {
  '2352a14b-b5fe-4a28-bdeb-46244c907db1': { title: 'Merge',
    description: 'Merge equal numbers to make bigger ones. Can you reach 2048? Simple rules, an endless puzzle.',
    controls: 'Push all tiles in one direction with the arrow keys or by swiping.' },
  '07825f82-9b15-403f-bbf4-4e7ffb427136': { title: 'Börü: The Last King',
    description: 'The saga of the last dragon fallen from the sky. Choose your dragon — Magma Börü, Ice Wyrm or Venom Viper — conquer hives, burn your enemies and grow your lair. Different worlds, costumes, a shop and a story mode await you.',
    controls: 'Steer the dragon with mouse / finger · Hold left click: fire · Space: ghost · E: roar · R: super plasma · Q+W: summon minion · 1-4: potion · M: map · Esc: pause' },
  '0c468808-6c14-4b27-87a4-fd68d3677a2f': { title: 'Sky Warrior',
    description: 'The sky is full of invaders! Shoot down wave after wave of enemies with your spaceship and collect yellow stars for double shots. Every wave is harder than the last.',
    controls: 'Drag your ship with your finger or mouse, or use the arrow keys. Firing is automatic.' },
  '9c79a130-b426-40cf-8026-db8efdb593f5': { title: 'Shadow Lab',
    description: 'Collect three samples and reach the exit without getting caught by the security lights. Use the walls, keep the alarm low and finish all three levels. Turkish and English are supported in the game.',
    controls: 'WASD / arrow keys: move · Avoid the light cones · TR/EN language button' },
  '0d0fdeeb-9e0a-410b-b90d-d805dde9e533': { title: 'Memory Master',
    description: 'Flip the cards and find the pairs. Wolf, eagle, tent, bow and arrow… Test your memory and set a record with the fewest moves.',
    controls: 'Tap or click the cards. Match two identical cards.' },
  '3dba6d4a-66c3-4372-8872-3019844098e7': { title: 'Tug of War',
    description: 'Two players on one phone: one taps from the bottom, one from the top, and whoever pulls the rope to their side fastest wins! Tap the glowing power rings to pull 6 times harder. Alone? Play against the computer on 3 difficulty levels.',
    controls: 'Tap your half of the screen as fast as you can · Tap a power ring: x6 pull · Keyboard: A (Red), L (Blue)' },
  '81e895d8-3939-467c-8e3f-1d210f7087a6': { title: 'KAPKAÇ',
    description: 'Grab the simit and run from the police! Dash through the back alleys of the Grand Bazaar, jump over obstacles and slide under them. The funniest runner game from Türkiye — how many simits can you snatch?',
    controls: 'Space / ↑: jump · ↓: slide · Press again in the air: double jump · Tap the screen on phones' },
  '3619b98b-8e12-4dae-bdb3-832d3452df3d': { title: 'Eagle Flight',
    description: 'Flap your wings and glide between the stone pillars. One-touch controls, but hard to master!',
    controls: 'Tap the screen, click or press Space to flap.' },
  'eb1d6065-1846-4584-9c2f-7897f0f2a710': { title: 'Kilim Blocks',
    description: 'Break blocks made of kilim patterns with the ball! 8 levels, each with a new pattern. Sturdy blocks need two hits to break.',
    controls: 'Slide the paddle with your finger or mouse (or ← →). Tap / Space to launch the ball.' },
  '6b817371-dd43-4f40-a077-1b07ed8b2bdc': { title: 'Wolf Run',
    description: 'You are a wolf running across the steppe in the moonlight. Jump over rocks and pine trees and dodge low-flying eagles. You get faster as you run; how far can you go?',
    controls: 'Tap the screen, press Space or ↑ to jump. Press again in the air to double jump.' },
  'af1a9be7-814a-4aa6-bc67-d3bc46b80693': { title: 'Nazar Değmesin',
    description: 'Dodge bad luck with your evil eye bead and collect good fortune! Run from Istanbul to Cappadocia, from Ephesus to Pamukkale; avoid black cats and broken mirrors, collect four-leaf clovers and gold.',
    controls: 'Tap / Space: jump' },
  'b40747e3-e7b0-4824-9c10-8740f2cb5f95': { title: 'Neon Snake',
    description: 'The classic snake game reborn in neon. Collect the pink lights and grow; the golden stars that appear now and then are worth 50 points! You can pass through walls, but don\'t hit yourself.',
    controls: 'Steer with the arrow keys / WASD. On phones, swipe in the direction you want.' },
  '5bae2761-fd9a-4609-a800-e5d6cd846bfd': { title: 'Reflex Duel',
    description: '2-4 players on one phone! When the screen turns green, the first to tap their own corner scores. Tap too early and you are out for the round and lose a point; watch out for the yellow trap! You can also play against the computer.',
    controls: 'Tap your zone when it turns green · Don\'t tap on yellow or red · Keyboard: A, L, G, P' },
  '78f1c497-1893-49ba-bbd5-e75536023ce3': { title: 'Restore & Sell',
    description: 'Join container auctions, clean up the old items you find inside, restore them and sell them for a profit. A relaxing trading and restoration game.',
    controls: 'Tap / click' },
  'bb8cc317-7c16-42ce-93c0-0bcda1ff0f1d': { title: 'Wind Harbor',
    description: 'Trade between four harbors with a small sailboat. Use the wind angle, avoid storms and reach 250 gold. Turkish and English are supported in the game.',
    controls: 'WASD / arrow keys: move · SPACE: buy/sell at a harbor · TR/EN language button' },
  'fc59a184-0a53-441f-bce7-9408d8568938': { title: 'SCORPY',
    description: 'Match marbles of the same color, pop them and reach the highest score! Combos, power-ups, daily quests and a multiplayer mode where you can compete with friends.',
    controls: 'Press and hold, drag to aim, release to shoot. Match 3 or more of the same color to pop them!' },
  '6905a4bf-4b36-4fe8-b836-ac83fc4034ed': { title: 'Stack Up!',
    description: 'Stack the blocks and build the tallest tower! Line them up exactly for a PERFECT, and chain perfects for a combo that grows your block. The game speeds up as the tower rises.',
    controls: 'Click / tap / Space: drop the block' },
};
